# Generated by Django 4.2.25 on 2025-10-08 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientdata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('rhoptions', models.CharField(choices=[('+', 'positive'), ('-', 'negative')], max_length=1)),
                ('unit', models.IntegerField()),
                ('location', models.TextField()),
                ('hospital', models.CharField(max_length=100)),
                ('ifany', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Donordetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('age', models.IntegerField()),
                ('bloodgroup', models.CharField(max_length=10)),
                ('rhoptions', models.CharField(choices=[('+', 'positive'), ('-', 'negative')], max_length=1)),
                ('unit', models.IntegerField()),
                ('location', models.TextField()),
                ('idproof', models.FileField(upload_to='idproof/')),
                ('mc', models.FileField(upload_to='medical_certificate/')),
                ('image', models.ImageField(upload_to='image/')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donors', to='bloodbankapp.patientdata')),
            ],
        ),
    ]
