# Generated by Django 4.2.25 on 2025-10-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0002_alter_donordetail_id_alter_patientdata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_email', models.EmailField(max_length=254, unique=True)),
                ('p_password', models.CharField(max_length=128)),
            ],
        ),
    ]
